apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-minikube
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-minikube
  interval: 10m
  path: ./apps/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 2m
